### PR TITLE
Fix issue#100: Download from ftp:// repos with limited max parallel connections is broken 

### LINKED ISSUE #100: Download from ftp:// repos with limited max parallel connections is broken
When FTP responses with message "421 There are too many connected users, please try later." then mirror is marked as tried and not used again for this target. If no more mirrors available then download fails.
Idea: Instead of failing use mirror again but use lower number of simultaneous connections to it.

### PR DESCRIPTION
**Pull request by jrohel**
Added allowed_parallel_connections for mirror.  
Each mirror has its own allowed_parallel_connections. Its value is set to
max_connection_per_host at the beginning. In the event of a temporary error (probably FTP responses with message "421 There are too many connected users, please try later.")
the value of allowed_parallel_connections is adjusted (reduced).
And mirror can be used later again (Download failed before this patch
if no more mirrors was available.).

### CODE REVIEW

File: librepo/downloader.c [hunk 1]
```diff
@@ -1660,6 +1676,22 @@ check_transfer_statuses(LrDownload *dd, GError **err)
                 // Truncate file - remove downloaded garbage (error html page etc.)
                 if (!truncate_transfer_file(target, err))
                     return FALSE;
+
+                if ((target->mirror->max_parallel_connections = -1 ||
```
Comment (mhatina) [inline librepo/downloader.c]: Missing '=', should be `target->mirror->max_parallel_connections == -1`.

File: librepo/downloader.c [hunk 2]
```diff
@@ -1660,6 +1676,22 @@ check_transfer_statuses(LrDownload *dd, GError **err)
...
+                     target->mirror->max_parallel_connections > 1) &&
+                    (target->mirror->running_transfers > 0 ||
+                     (target->mirror->successful_transfers > 0 &&
+                      target->mirror->failed_transfers < dd->max_connection_per_host)))
```
Comment (mhatina) [inline librepo/downloader.c]: I would refactor the conditions to be cleaner. Right now it is hard to understand what it does.

**Comment by jrohel** [comment]
I made changes in code. Conditions were simplified.

File: librepo/downloader.c [hunk 3]
```diff
@@ -1648,19 +1673,43 @@ check_transfer_statuses(LrDownload *dd, GError **err)
...
-                if (!truncate_transfer_file(target, err))
-                    return FALSE;
-            } else {
+                !target->target->baseurl)
+            {   
+              
+                // Another transfers are running or there are successful transfers
+                // and fewer failed transfers than tried parallel connections. It may be mirror is OK
+                // but accepts fewer parallel connections.
+                if (target->mirror->running_transfers > 0 ||
```
Comment (mhatina) [inline librepo/downloader.c]: How about `return has_running_transfers(target) || (has_successful_transfers(target) && !has_less_failed_transfers_than_tried_parallel_connections(target));` in `decide_to_lower_max_tried_parallel_conections()` function?

File: librepo/downloader.c [hunk 4]
```diff
@@ -1648,19 +1673,43 @@ check_transfer_statuses(LrDownload *dd, GError **err)
...
+                    (target->mirror->successful_transfers > 0 &&
+                      target->mirror->failed_transfers < target->mirror->max_tried_parallel_connections))
+                {
+                    g_debug("%s: Lower maximum of allowed parallel connections for this mirror", __func__);
+                    if (target->mirror->running_transfers > 0)
```
Comment (mhatina) [inline librepo/downloader.c]: `has_running_transfers(target)` from above?

File: librepo/downloader.c [hunk 5]
```diff
@@ -1648,19 +1673,43 @@ check_transfer_statuses(LrDownload *dd, GError **err)
...
+                        target->mirror->allowed_parallel_connections = target->mirror->running_transfers;
+                    else
+                        target->mirror->allowed_parallel_connections = 1;
+
+                    // Give used mirror another chance
+                    target->tried_mirrors = g_slist_remove(target->tried_mirrors, target->mirror);
+                    num_of_tried_mirrors = g_slist_length(target->tried_mirrors);
+                }
+
+                if (dd->max_mirrors_to_try <= 0 ||
```
Comment (mhatina) [inline librepo/downloader.c]: `is_max_mirrors_unlimited() || has_mirrors_to_try()` ?

File: librepo/downloader.c (hunk 3 above)
Comment (jrohel) [inline librepo/downloader.c]: downloader.c contains very long functions now. You prefer another extreme approach. A lot of very short (sometime one line) functions. Eg. has_running_transfers(mirror) will be contain only one line "return mirror->running_transfers > 0". Yes I know, short functions are more descriptive. OK, I can try change style of new code in downloader.c I will prepare new commit.

**Comment by jrohel** [comment]
Code refactored to small functions.
